### Linear Algebra

- Matrices
- opertions on matrices: dot product, componentwise multiplication, transpose
- Determinant
- Rank of a matrix
- Inverse of a matrix
- Eigen values and Eigen vectors
- Solving the system of equations
- Singular Value Decomposition (SVD)
- LA [Documentation](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [95]:
#creating a list  
lst = [2, 3, 4]

In [96]:
lst


[2, 3, 4]

In [97]:
lst*2

[2, 3, 4, 2, 3, 4]

In [6]:
import numpy as np 
list = np.array([2,3,4])
list

array([2, 3, 4])

In [7]:
list*2

array([4, 6, 8])

In [9]:
list = np.array([2,3])
list*2

array([4, 6])

In [10]:
list = [2,3,4]
list*2

[2, 3, 4, 2, 3, 4]

In [14]:
#create a numpy array
list = np.array([1,2,3])
ls = [1,2,3] 
np.array(ls)
print(ls)

[1, 2, 3]


In [20]:
ls1=np.array([1,2,3])
ls2 = np.array([4,2,6])  
ls1*ls2  

array([ 4,  4, 18])

In [21]:
ls1/ls2

array([0.25, 1.  , 0.5 ])

In [22]:
#scalar multiplication
2*ls2

array([ 8,  4, 12])

In [23]:
ls2/4

array([1. , 0.5, 1.5])

In [99]:
#2d-array
A = np.array([[10,2],[2,1],[3,1]])
print(A)

[[10  2]
 [ 2  1]
 [ 3  1]]


In [108]:
#dimension of a matrix 
print(f"The dimension of A is {A.ndim}") 
#shape of a matrix  
print(f"Shape of A is {A.shape}")
#flatten the matrix A
print(f"Flatten of A is {A.flatten()}")
#transpose of A 
print(f"Transpose of A is:\n A^T = {A.T}")

The dimension of A is 2
Shape of A is (3, 2)
Flatten of A is [10  2  2  1  3  1]
Transpose of A is:
 A^T = [[10  2  3]
 [ 2  1  1]]


In [45]:
#Transpose
np.transpose(A)

array([[10,  2,  3],
       [ 2,  1,  1]])

The dot product of two vectors defined as 
                $$a.b = ab^T$$
$a=(x_1,y_1), b=(x_2,y_2)$ then $$a.b=x_1x_2+y_1y_2$$

In [46]:
a = np.array([1,2,3])
b= np.array([2,-1,3])
# Dot product
np.dot(a,b)

9

In [47]:
#componentwise multiplication
np.multiply(a,b)

array([ 2, -2,  9])

In [109]:
A=[[1,2],[2,1]]
B=[[1,-2],[-2,1]]  
A= np.array(A)
B= np.array(B)
#dot product of two matrices
np.dot(A,B)

array([[-3,  0],
       [ 0, -3]])

In [110]:
#Matrix multiplication
# For 2-D array the matrix multiplication and dot products are same
np.dot(A,B)
A@B
np.matmul(A,B)

array([[-3,  0],
       [ 0, -3]])

In [111]:
print(f"The matrix A is:\n {A}")
print(f"The matrix B is:\n {B}")

The matrix A is:
 [[1 2]
 [2 1]]
The matrix B is:
 [[ 1 -2]
 [-2  1]]


In [113]:
# Componentwise matrix multiplication
np.multiply(A,B)

array([[ 1, -4],
       [-4,  1]])

In [75]:
A = np.array([1,2])
np.dot(A,B)

array([-3,  0])

In [76]:
np.matmul(A,B)

array([-3,  0])

In [72]:
x= np.array([1,2])
y = np.array([[2,3],[0,1]])  

In [74]:
#
np.dot(x,y)
np.matmul(x,y)

array([2, 5])

In [82]:
#numpy-->linalg--> det, eig, rank....
np.linalg.det(B)

-2.9999999999999996

In [84]:
from numpy import linalg as la 
la.det(B)

-2.9999999999999996

In [85]:
# To compute the rank of the matrix
la.matrix_rank(B)

2

In [131]:
# Compute inverse of a matrix 
la.inv(B)

array([[-0.33333333, -0.66666667],
       [-0.66666667, -0.33333333]])

$Av=\lambda v$

In [132]:
#eigenvalues and eigenvectors
eg, ev =la.eig(B)
print(ev)

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


- The eigen vectors are normalized 
- The columns are eigen vectors corresponding to eigen values  

In [130]:
#First eigen vector

v0 = ev[:,0]
v1 = ev[:,1]  
lambda1 = B@v0@v0.T
lambda2 = B@v1@v1.T
print(f'$\lambda_1$ = {lambda1:.2f}, $\lambda_2$={lambda2:.2f}')

$\lambda_1$ = 3.00, $\lambda_2$=-1.00


#The role of eigen values and Eigen Vectors
- Dimentional reduction - PCA
- Image Resolutions  
- Text Analysis 

In [133]:
#trace of a matrix
np.trace(B)

2


#### Solving the system of equations:
2x+3y=5

4x-y = 7

To solve we Ax=b


In [134]:
A = np.array([[2,3],[4,-1]])
b=np.array([5,7])
x,y=la.solve(A,b)
print(f"x = {x:.2f} and y = {y:.2f}")

x = 1.86 and y = 0.43
